{"uid":"223da9a3d16ab0d7","name":"Verify scans are returned correctly for a valid chatbot ID -- @1.1 ","fullName":"Get Scans by Chatbot ID using Genr3d API: Verify scans are returned correctly for a valid chatbot ID","historyId":"b9effca286996308b3291f82629baf1a","time":{"start":1757682266654,"stop":1757682270961,"duration":4307},"status":"failed","statusMessage":"AssertionError: Expected <SCAN_IN_PROGRESS> to be equal to <REPORT_GENERATED>, but was not.\n","statusTrace":"  File \"C:\\Users\\Noman\\PycharmProjects\\generativesecurity\\.venv\\Lib\\site-packages\\behave\\model.py\", line 1991, in run\n    match.run(runner.context)\n  File \"C:\\Users\\Noman\\PycharmProjects\\generativesecurity\\.venv\\Lib\\site-packages\\behave\\matchers.py\", line 105, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\Get_all_scans_of_a_chatbot_by_chatbotID.py\", line 73, in step_impl\n    assert_that(status).is_equal_to(\"REPORT_GENERATED\")\n  File \"C:\\Users\\Noman\\PycharmProjects\\generativesecurity\\.venv\\Lib\\site-packages\\assertpy\\base.py\", line 126, in is_equal_to\n    self.error('Expected <%s> to be equal to <%s>, but was not.' % (self.val, other))\n  File \"C:\\Users\\Noman\\PycharmProjects\\generativesecurity\\.venv\\Lib\\site-packages\\assertpy\\assertpy.py\", line 433, in error\n    raise AssertionError(out)\n","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":1,"retriesStatusChange":true,"beforeStages":[],"testStage":{"status":"failed","statusMessage":"AssertionError: Expected <SCAN_IN_PROGRESS> to be equal to <REPORT_GENERATED>, but was not.\n","statusTrace":"  File \"C:\\Users\\Noman\\PycharmProjects\\generativesecurity\\.venv\\Lib\\site-packages\\behave\\model.py\", line 1991, in run\n    match.run(runner.context)\n  File \"C:\\Users\\Noman\\PycharmProjects\\generativesecurity\\.venv\\Lib\\site-packages\\behave\\matchers.py\", line 105, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\Get_all_scans_of_a_chatbot_by_chatbotID.py\", line 73, in step_impl\n    assert_that(status).is_equal_to(\"REPORT_GENERATED\")\n  File \"C:\\Users\\Noman\\PycharmProjects\\generativesecurity\\.venv\\Lib\\site-packages\\assertpy\\base.py\", line 126, in is_equal_to\n    self.error('Expected <%s> to be equal to <%s>, but was not.' % (self.val, other))\n  File \"C:\\Users\\Noman\\PycharmProjects\\generativesecurity\\.venv\\Lib\\site-packages\\assertpy\\assertpy.py\", line 433, in error\n    raise AssertionError(out)\n","steps":[{"name":"Given User sends GET request to fetch scans for chatbot ID \"89ebd370-38bb-43e5-9956-5c8cda370b9c\"","time":{"start":1757682266655,"stop":1757682270931,"duration":4276},"status":"passed","steps":[],"attachments":[],"parameters":[],"hasContent":false,"shouldDisplayMessage":false,"attachmentsCount":0,"stepsCount":0,"attachmentStep":false},{"name":"When the user receives the scans response","time":{"start":1757682270931,"stop":1757682270933,"duration":2},"status":"passed","steps":[],"attachments":[],"parameters":[],"hasContent":false,"shouldDisplayMessage":false,"attachmentsCount":0,"stepsCount":0,"attachmentStep":false},{"name":"Then the status code returned should be 200 for successful scans retrieval","time":{"start":1757682270935,"stop":1757682270936,"duration":1},"status":"passed","steps":[],"attachments":[],"parameters":[],"hasContent":false,"shouldDisplayMessage":false,"attachmentsCount":0,"stepsCount":0,"attachmentStep":false},{"name":"And the response should contain a list of scans","time":{"start":1757682270937,"stop":1757682270941,"duration":4},"status":"passed","steps":[],"attachments":[],"parameters":[],"hasContent":false,"shouldDisplayMessage":false,"attachmentsCount":0,"stepsCount":0,"attachmentStep":false},{"name":"And each scan should contain a valid \"scan_id\" of length 36","time":{"start":1757682270942,"stop":1757682270944,"duration":2},"status":"passed","steps":[],"attachments":[],"parameters":[],"hasContent":false,"shouldDisplayMessage":false,"attachmentsCount":0,"stepsCount":0,"attachmentStep":false},{"name":"And each scan should contain a \"creation_timestamp\" in ISO 8601 format","time":{"start":1757682270944,"stop":1757682270946,"duration":2},"status":"passed","steps":[],"attachments":[],"parameters":[],"hasContent":false,"shouldDisplayMessage":false,"attachmentsCount":0,"stepsCount":0,"attachmentStep":false},{"name":"And each scan should have a \"status\" equal to \"REPORT_GENERATED\"","time":{"start":1757682270946,"stop":1757682270959,"duration":13},"status":"failed","statusMessage":"AssertionError: Expected <SCAN_IN_PROGRESS> to be equal to <REPORT_GENERATED>, but was not.\n","statusTrace":"  File \"C:\\Users\\Noman\\PycharmProjects\\generativesecurity\\.venv\\Lib\\site-packages\\behave\\model.py\", line 1991, in run\n    match.run(runner.context)\n  File \"C:\\Users\\Noman\\PycharmProjects\\generativesecurity\\.venv\\Lib\\site-packages\\behave\\matchers.py\", line 105, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\Get_all_scans_of_a_chatbot_by_chatbotID.py\", line 73, in step_impl\n    assert_that(status).is_equal_to(\"REPORT_GENERATED\")\n  File \"C:\\Users\\Noman\\PycharmProjects\\generativesecurity\\.venv\\Lib\\site-packages\\assertpy\\base.py\", line 126, in is_equal_to\n    self.error('Expected <%s> to be equal to <%s>, but was not.' % (self.val, other))\n  File \"C:\\Users\\Noman\\PycharmProjects\\generativesecurity\\.venv\\Lib\\site-packages\\assertpy\\assertpy.py\", line 433, in error\n    raise AssertionError(out)\n","steps":[],"attachments":[],"parameters":[],"hasContent":true,"shouldDisplayMessage":true,"attachmentsCount":0,"stepsCount":0,"attachmentStep":false}],"attachments":[],"parameters":[],"hasContent":true,"shouldDisplayMessage":false,"attachmentsCount":0,"stepsCount":7,"attachmentStep":false},"afterStages":[],"labels":[{"name":"severity","value":"normal"},{"name":"tag","value":"Test"},{"name":"feature","value":"Get Scans by Chatbot ID using Genr3d API"},{"name":"framework","value":"behave"},{"name":"language","value":"cpython3"},{"name":"resultFormat","value":"allure2"}],"parameters":[{"name":"chatbot_id","value":"89ebd370-38bb-43e5-9956-5c8cda370b9c"}],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[{"uid":"b2ff35c2980dbb9b","status":"broken","statusDetails":"requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://identitytoolkit.googleapis.com/v1/accounts:signInWithPassword?key=AIzaSyD08yxn7V_YAfkAY8mKDTYjfKV_qoPrdRQ\n","time":{"start":1757682172922,"stop":1757682173449,"duration":527}}],"categories":[{"name":"Product defects","matchedStatuses":[]}],"tags":["Test"]},"source":"223da9a3d16ab0d7.json","parameterValues":["89ebd370-38bb-43e5-9956-5c8cda370b9c"]}