{"name": "Validate successful update of chatbot API details -- @1.1 ", "status": "broken", "statusDetails": {"message": "requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://identitytoolkit.googleapis.com/v1/accounts:signInWithPassword?key=AIzaSyD08yxn7V_YAfkAY8mKDTYjfKV_qoPrdRQ\n", "trace": "  File \"C:\\Users\\Noman\\PycharmProjects\\generativesecurity\\.venv\\Lib\\site-packages\\behave\\model.py\", line 1991, in run\n    match.run(runner.context)\n  File \"C:\\Users\\Noman\\PycharmProjects\\generativesecurity\\.venv\\Lib\\site-packages\\behave\\matchers.py\", line 105, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\FireBase_Update_API_Information_of_an_existing_chatbot.feature.py\", line 22, in step_impl\n    id_token = get_firebase_id_token()\n               ^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Noman\\PycharmProjects\\generativesecurity\\utilities\\authentication.py\", line 16, in get_firebase_id_token\n    response.raise_for_status()  # Raise an error for non-2xx responses\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Noman\\PycharmProjects\\generativesecurity\\.venv\\Lib\\site-packages\\requests\\models.py\", line 1026, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\n"}, "steps": [{"name": "Given FireBase_User sends PUT request to update chatbot API details for chatbot ID with environment ID and endpoint \"http://34.36.66.146/stream_messages\"", "status": "broken", "statusDetails": {"message": "requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://identitytoolkit.googleapis.com/v1/accounts:signInWithPassword?key=AIzaSyD08yxn7V_YAfkAY8mKDTYjfKV_qoPrdRQ\n", "trace": "  File \"C:\\Users\\Noman\\PycharmProjects\\generativesecurity\\.venv\\Lib\\site-packages\\behave\\model.py\", line 1991, in run\n    match.run(runner.context)\n  File \"C:\\Users\\Noman\\PycharmProjects\\generativesecurity\\.venv\\Lib\\site-packages\\behave\\matchers.py\", line 105, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\FireBase_Update_API_Information_of_an_existing_chatbot.feature.py\", line 22, in step_impl\n    id_token = get_firebase_id_token()\n               ^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Noman\\PycharmProjects\\generativesecurity\\utilities\\authentication.py\", line 16, in get_firebase_id_token\n    response.raise_for_status()  # Raise an error for non-2xx responses\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Noman\\PycharmProjects\\generativesecurity\\.venv\\Lib\\site-packages\\requests\\models.py\", line 1026, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\n"}, "start": 1757682177159, "stop": 1757682177807}, {"name": "When FireBase_the user receives the chatbot API update response", "status": "skipped", "start": 1757682177815, "stop": 1757682177815}, {"name": "Then FireBase_the status code returned should be 200 for successful update", "status": "skipped", "start": 1757682177815, "stop": 1757682177815}, {"name": "And FireBase_the response should contain a valid chatbotID", "status": "skipped", "start": 1757682177815, "stop": 1757682177815}, {"name": "And FireBase_the response should contain a \"status\" equal to \"API_updated\"", "status": "skipped", "start": 1757682177815, "stop": 1757682177815}], "parameters": [{"name": "chatbot_url", "value": "http://34.36.66.146/stream_messages"}], "start": 1757682177158, "stop": 1757682177815, "uuid": "3e37543c-c4ed-4b3a-bce7-076614620859", "historyId": "506910af4d3e294515e00e35b629cc36", "fullName": "Update Chatbot API Details using Genr3d API: Validate successful update of chatbot API details", "labels": [{"name": "severity", "value": "normal"}, {"name": "tag", "value": "Test"}, {"name": "feature", "value": "Update Chatbot API Details using Genr3d API"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}], "titlePath": ["features", "Update Chatbot API Details using Genr3d API"]}