{"name": "Validate findings response for invalid scan ID format -- @1.1 ", "status": "broken", "statusDetails": {"message": "requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://identitytoolkit.googleapis.com/v1/accounts:signInWithPassword?key=AIzaSyD08yxn7V_YAfkAY8mKDTYjfKV_qoPrdRQ\n", "trace": "  File \"C:\\Users\\Noman\\PycharmProjects\\generativesecurity\\.venv\\Lib\\site-packages\\behave\\model.py\", line 1991, in run\n    match.run(runner.context)\n  File \"C:\\Users\\Noman\\PycharmProjects\\generativesecurity\\.venv\\Lib\\site-packages\\behave\\matchers.py\", line 105, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\FireBase_Get_all_findings_for_a_given_scan.py\", line 20, in step_impl\n    id_token = get_firebase_id_token()\n               ^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Noman\\PycharmProjects\\generativesecurity\\utilities\\authentication.py\", line 16, in get_firebase_id_token\n    response.raise_for_status()  # Raise an error for non-2xx responses\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Noman\\PycharmProjects\\generativesecurity\\.venv\\Lib\\site-packages\\requests\\models.py\", line 1026, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\n"}, "steps": [{"name": "Given FireBase_User sends GET request to fetch findings for scan ID \"invalid\"", "status": "broken", "statusDetails": {"message": "requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://identitytoolkit.googleapis.com/v1/accounts:signInWithPassword?key=AIzaSyD08yxn7V_YAfkAY8mKDTYjfKV_qoPrdRQ\n", "trace": "  File \"C:\\Users\\Noman\\PycharmProjects\\generativesecurity\\.venv\\Lib\\site-packages\\behave\\model.py\", line 1991, in run\n    match.run(runner.context)\n  File \"C:\\Users\\Noman\\PycharmProjects\\generativesecurity\\.venv\\Lib\\site-packages\\behave\\matchers.py\", line 105, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\FireBase_Get_all_findings_for_a_given_scan.py\", line 20, in step_impl\n    id_token = get_firebase_id_token()\n               ^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Noman\\PycharmProjects\\generativesecurity\\utilities\\authentication.py\", line 16, in get_firebase_id_token\n    response.raise_for_status()  # Raise an error for non-2xx responses\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Noman\\PycharmProjects\\generativesecurity\\.venv\\Lib\\site-packages\\requests\\models.py\", line 1026, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\n"}, "start": 1757682171092, "stop": 1757682171720}, {"name": "When FireBase_the user receives the findings response", "status": "skipped", "start": 1757682171725, "stop": 1757682171725}, {"name": "Then FireBase_the status code returned should be 400 for bad request error", "status": "skipped", "start": 1757682171726, "stop": 1757682171726}, {"name": "And FireBase_the response should contain an error message \"Bad Request\"", "status": "skipped", "start": 1757682171726, "stop": 1757682171726}, {"name": "And FireBase_the message should contain \"Invalid input:\"", "status": "skipped", "start": 1757682171726, "stop": 1757682171726}], "parameters": [{"name": "scan_id", "value": "invalid"}], "start": 1757682171090, "stop": 1757682171726, "uuid": "86941fc3-28cb-40df-9959-40be1138c920", "historyId": "896aa11ab8f2b3d4830664b7d7a74fef", "fullName": "Get Findings by Scan ID using Genr3d API: Validate findings response for invalid scan ID format", "labels": [{"name": "severity", "value": "normal"}, {"name": "tag", "value": "Negative"}, {"name": "tag", "value": "Test"}, {"name": "feature", "value": "Get Findings by Scan ID using Genr3d API"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}], "titlePath": ["features", "Get Findings by Scan ID using Genr3d API"]}